INSERT INTO department (name)
VALUES ("Administration/Operations"),
    ("Research and Development"),
    ("Marketing and Sales"),
    ("Accounting and Finance"),
    ("Legal");
INSERT INTO role (title, salary, department_id)
VALUES ("Chief Executive Officer", 800000, 1),
    ("Chief Technology Officer", 1250000, 1),
    ("President", 280000, 1),
    ("Executive Assistant", 82000, 1),
    ("Lead Engineer", 130000, 2),
    ("Software engineer", 100000, 2),
    ("Sales Lead", 190000, 3),
    ("Project Manager", 130000, 3),
    ("Sales Representative", 50000, 3),
    ("Finance Manager", 150000, 4),
    ("Accountant", 87000, 4),
    ("Legal Team Lead", 108000, 5),
    ("Lawyer", 71000, 5);
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ("Peggy", "Tamas", 8, NULL),
    ("Haris", "Császár", 6, 5),
    ("Arata", "Samuel", 12, NULL),
    ("Severina", "Dedrick", 13, 12),
    ("Tófa", "Bátori", 6, 5),
    ("Cai", "Ó Seighin", 2, NULL),
    ("Cassian", "Popa", 11, 10),
    ("Firdous", "Fujimoto", 1, NULL),
    ("Ananta", "Schultheis", 4, 3),
    ("Sauli", "Sultana", 7, NULL),
    ("Gavriel", "Bosko", 9, 7),
    ("Sanford", "Filipek", 3, 1),
    ("Embla", "MacClellan", 4, 3),
    ("Edvard", "Clistephan", 9, 7),
    ("Poseidon", "Parish", 3, 1),
    ("Cyrus", "Reich", 5, 2),
    ("Maglocunos", "Hájek", 9, 7),
    ("Metztli", "Deering", 6, 5),
    ("Ler", "Vilar", 11, 10),
    ("Padmini", "Schwangau", 10, NULL);